# Basics config file. READ Config-README.txt.
is-beta-version: false
server-owners: Console
message: This is a survival server!
download-latest-version: true
auto-update: true
teleport-requests: true
tag-playing-time-minutes: 30
disallow-gamemode-change: false