name: Basics
main: coolawesomeme.basics_plugin.Basics
version: 0.7.2
description: A bukkit plugin that offers/ will offer many essential and fun commands.
author: coolawesomeme
website: http://coolawesomeme.github.io/Basics

commands:
  serverhelp:
    description: This command gets you started on the server, as well as gives you basic items.
    usage: "Usage: /<command> [playerName]"
    aliases: [server-help, shelp]
    permission: basics.serverhelp
  brb:
    description: Can only be used by server console, or the owner. For regular users, use /afk .
    usage: "Usage: /<command> [true/false]"
  banroulette:
    description: Randomly bans a player for 30 mins.
    usage: "Usage: /<command>"
    permission: basics.banroulette
  banhammer:
    description: Surprise!
    usage: "Usage: /<command>"
    permission: basics.banhammer
  tproulette:
    description: Puts a player or all players at random coordinates.
    usage: "Usage: /<command> [playerName/all] [world]"
    aliases: teleportroulette
    permission: basics.tproulette
  tpr:
    description: Requests to teleport to a user, or allows to accept/ decline a teleport request.
    usage: "Usage: /<command> [playerName/accept/decline/setRequest <true/false>]"
    aliases: [teleportrequest, tprequest]
    permission: basics.tpr
  lockdown:
    description: Puts the server into lockdown mode. Null removes the lockdown, mild kicks incoming players & severe kicks incoming and currently connected players.
    usage: "Usage: /<command> [null/mild/severe/status]"
    permission: basics.lockdown.status
  tag:
    description: Starts tag, where one player is the tagger, and has to tag every player on the server
    usage: "Usage: /<command> [end]"
    permission: basics.tag

permissions:
   basics.all:
     description: Gives access to all Basics commands
     default: false
     children:
       basics.admin: true
       basics.banroulette: true
       basics.banhammer: true
       basics.tproulette.all: true
       basics.lockdown: true
   basics.admin.full:
     description: Access to admin + a few other exclusive permissions
     default: false
     children:
       basics.all: true
       basics.gamemode_ban.change: true
   basics.admin:
     description: Gives access to all admin-only commands
     default: op
     children:
       basics.banroulette: true
       basics.banhammer: true
       basics.tproulette.all: true
       basics.tpr.setrequest: true
       basics.tag.end: true
   basics.serverhelp:
     description: Allows access of severhelp command
     default: true
   basics.banroulette:
     description: Allows access of banroulette command
     default: op
   basics.banhammer:
     description: Allows access of banhammer command
     default: op
   basics.tproulette:
     description: Allows access of tproulette command
     default: true
   basics.tproulette.all:
     description: Allows access to tproulette all players
     default: op
     children:
       basics.tproulette: true
   basics.tpr:
     description: Allows access of tpr command
     default: true
   basics.tpr.setrequest:
     description: Allows access to set whether requests are needed
     default: op
     children:
       basics.tpr: true
   basics.lockdown:
     description: Allows access of lockdown command
     default: op
     children:
       basics.lockdown.status: true
   basics.lockdown.status:
     description: Allows access to current threat level
     default: true
   basics.tag:
     description: Allows access of tag command
     default: true
   basics.tag.end:
     description: Allows access to end tag
     default: op
     children:
       basics.tag: true
   basics.gamemode_ban.change:
     description: Allows changing of gamemode, even if disallowing of gamemode changing is on
     default: false